### ISSUE TITLE
Getting ValueError: on running the training code of Refign

### ISSUE THREAD

**Issue by nineRishav** [brdav/refign#10]
root@7f4a0fe182ea:/workspace/refign# `python tools/run.py fit --config configs/cityscapes_acdc/refign_hrda_star.yaml --trainer.gpus 1 --trainer.precision 16 `

Global seed set to 0
/opt/conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
_Rishav is printing  /workspace/refign/models/correlation_ops_
Using 16bit native Automatic Mixed Precision (AMP)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
Traceback (most recent call last):
  File "tools/run.py", line 4, in <module>
    ConditioningLightningCLI(pl.LightningModule,
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 528, in __init__
    self._run_subcommand(self.subcommand)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 783, in _run_subcommand
    fn(**fn_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1138, in _run
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1438, in _call_setup_hook
    self.datamodule.setup(stage=fn)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py", line 474, in wrapped_fn
    fn(*args, **kwargs)
  File "/workspace/refign/data_modules/combined_data_module.py", line 166, in setup
    self.train_ds.append(globals()[ds](
  File "/workspace/refign/data_modules/datasets/cityscapes.py", line 98, in __init__
    self.paths['semantic'].index(os.path.expandvars(file)))
**ValueError: '/workspace/refign/data/DATA_DIR/Cityscapes/gtFine/train/dusseldorf/dusseldorf_000162_000019_gtFine_labelTrainIds.png' is not in list**

**Comment by brdav** [comment]
As mentioned in the README you have to set the environment variable $DATA_DIR.

**Comment by nineRishav** [comment]
Thanks for taking the time to answer promptly. 
I was running on the docker, so I messed up the DATA_DIR path.

Issue solved.

**Comment by RyanQR** [comment]
> Thanks for taking the time to answer promptly. I was running on the docker, so I messed up the DATA_DIR path.
> 
> Issue solved.

Hi, I also use docker to run the code. I ran into the same problem as you, but I tried to change the path to DATA_DIR and got "ValueError: 'data/cityscapes/gtFine/train/Strasbourg touched/strasbourg_000001_029980_gtFine_labelTrainIds PNG' is not in the list." How did you change it?
