### ISSUE TITLE
KeyError: '_results' | Unable to find _results in checkpoint 

### ISSUE THREAD

**Issue by nineRishav** [brdav/refign#9]
I am getting error when running the code

root@7f4a0fe182ea:/workspace/refign# `python tools/run.py test --config configs/cityscapes_acdc/refign_hrda_star.yaml --ckpt_path pretrained_models/refign_hrda_star_acdc.ckpt --trainer.gpus 1 `
Global seed set to 0
/opt/conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Rishav is printing  /workspace/refign/models/correlation_ops
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
Restoring states from the checkpoint path at pretrained_models/refign_hrda_star_acdc.ckpt
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
Missing logger folder: lightning_logs/refign_hrda_daformer_cs_acdc
Traceback (most recent call last):
  File "tools/run.py", line 4, in <module>
    ConditioningLightningCLI(pl.LightningModule,
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 528, in __init__
    self._run_subcommand(self.subcommand)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/cli.py", line 783, in _run_subcommand
    fn(**fn_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 911, in test
    return self._call_and_handle_interrupt(self._test_impl, model, dataloaders, ckpt_path, verbose, datamodule)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 954, in _test_impl
    results = self._run(model, ckpt_path=self.tested_ckpt_path)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1194, in _run
    self.checkpoint_connector.restore_training_state()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 191, in restore_training_state
    self.restore_loops()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 224, in restore_loops
    self.trainer.test_loop.load_state_dict(state_dict["test_loop"])
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 252, in load_state_dict
    self._load_from_state_dict(state_dict.copy(), prefix, metrics)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 281, in _load_from_state_dict
    state_dict[prefix + k], metrics=metric_attributes, sync_fn=self.trainer.training_type_plugin.reduce
**KeyError: '_results'**

**Comment by brdav** [comment]
Thank you for pointing this out. I repaired the HRDA checkpoints, so the loading should work now.
